# Generated by Django 6.0.2 on 2026-02-23 04:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount'), ('bonus', 'Bonus Credit')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage or fixed amount', max_digits=10)),
                ('min_deposit', models.DecimalField(decimal_places=2, default=0, help_text='Minimum deposit to use coupon', max_digits=15)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount', max_digits=15, null=True)),
                ('uses_limit', models.IntegerField(default=0, help_text='0 = unlimited')),
                ('uses_count', models.IntegerField(default=0)),
                ('uses_per_user', models.IntegerField(default=1, help_text='How many times each user can use')),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountUpgrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_tier', models.CharField(max_length=20)),
                ('requested_tier', models.CharField(choices=[('intermediate', 'Intermediate - $500'), ('advanced', 'Advanced - $2,000'), ('vip', 'VIP - $10,000')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(default='balance', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid - Awaiting Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_upgrades', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Upgrade',
                'verbose_name_plural': 'Account Upgrades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('experience', models.TextField(help_text='Describe your experience in finance/investments')),
                ('marketing_plan', models.TextField(help_text='How will you promote Elite Wealth Capita?')),
                ('expected_referrals', models.IntegerField(help_text='Expected monthly referrals')),
                ('social_media_links', models.TextField(blank=True, help_text='Your social media profiles')),
                ('website', models.URLField(blank=True)),
                ('id_document', models.ImageField(blank=True, null=True, upload_to='agent_docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Commission % on referral investments', max_digits=5)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_agent_apps', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Application',
                'verbose_name_plural': 'Agent Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='investments.coupon')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usage', to='investments.deposit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Monthly interest rate %', max_digits=5)),
                ('duration_days', models.IntegerField(choices=[(30, '30 Days'), (60, '60 Days'), (90, '90 Days'), (180, '6 Months'), (365, '12 Months')])),
                ('total_repayment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_repaid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('purpose', models.TextField(blank=True)),
                ('collateral_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('repaying', 'Repaying'), ('completed', 'Completed'), ('defaulted', 'Defaulted')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(default='balance', max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='investments.loan')),
            ],
            options={
                'verbose_name': 'Loan Repayment',
                'verbose_name_plural': 'Loan Repayments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(blank=True, max_length=19, unique=True)),
                ('cvv', models.CharField(blank=True, max_length=3)),
                ('expiry_month', models.IntegerField(default=12)),
                ('expiry_year', models.IntegerField(default=2028)),
                ('card_type', models.CharField(choices=[('standard', 'Standard Card'), ('premium', 'Premium Card'), ('platinum', 'Platinum Card')], default='standard', max_length=20)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('billing_address', models.TextField(blank=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=1000, max_digits=15)),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=10000, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('frozen', 'Frozen'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_online_enabled', models.BooleanField(default=True)),
                ('is_international_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Virtual Card',
                'verbose_name_plural': 'Virtual Cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
