# Generated by Django 6.0.2 on 2026-03-06 03:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_coupon_accountupgrade_agentapplication_couponusage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='notes',
            field=models.TextField(blank=True, help_text='Admin notes about this investment'),
        ),
        migrations.AddField(
            model_name='investment',
            name='profit_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentapplication',
            name='marketing_plan',
            field=models.TextField(help_text='How will you promote Elite Wealth Capital?'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='investments_code_338900_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'expires_at'], name='investments_is_acti_d8760c_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['user', 'status'], name='investments_user_id_dfb69f_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['status'], name='investments_status_483e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'status'], name='investments_user_id_352b49_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['status'], name='investments_status_8a7490_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['end_date'], name='investments_end_dat_f4d9eb_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'status'], name='investments_user_id_436805_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='investments_status_9b1b51_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['due_date'], name='investments_due_dat_48c319_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['user', 'status'], name='investments_user_id_221d90_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['status'], name='investments_status_463cb8_idx'),
        ),
    ]
