# Generated by Django 4.2.29 on 2026-03-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_investmentplan_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Trading symbol, e.g. BTC, ETH', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name, e.g. Bitcoin, Ethereum', max_length=100)),
                ('coingecko_id', models.CharField(help_text='CoinGecko coin ID (e.g. bitcoin, ethereum)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crypto Ticker',
                'verbose_name_plural': 'Crypto Tickers',
                'ordering': ['display_order', 'symbol'],
            },
        ),
    ]
