# Generated by Django 4.2.29 on 2026-03-28 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_add_crypto_ticker'),
        ('investments', '0005_remove_virtualcard_cvv_alter_coupon_discount_value_and_more'),
    ]

    operations = [
    ]
