# Generated by Django 4.2.29 on 2026-03-14 12:15

from django.db import migrations
from django.utils import timezone


SAMPLE_ARTICLES = [
    {
        "title": "Q1 2026 Market Outlook: What Investors Need to Know",
        "slug": "q1-2026-market-outlook",
        "excerpt": "Our investment team analyzes the key trends shaping markets in the first quarter of 2026. From cryptocurrency regulations to traditional market movements, here's what smart investors are watching.",
        "content": "<p>As we enter Q1 2026, the global investment landscape is shifting rapidly. Institutional adoption of digital assets continues to accelerate, with several major pension funds allocating a portion of their portfolios to Bitcoin and Ethereum.</p><h2>Key Trends to Watch</h2><ul><li><strong>Regulatory Clarity:</strong> Major economies are finalising crypto asset frameworks, providing long-awaited certainty for institutional investors.</li><li><strong>AI-Driven Trading:</strong> Machine learning algorithms now account for an estimated 70% of daily crypto trading volume.</li><li><strong>Stablecoin Growth:</strong> USDT and USDC market caps have hit new highs as investors seek yield in volatile markets.</li></ul><p>Elite Wealth Capital's diversified investment plans are designed to capture upside in each of these trends while managing downside risk through our proprietary portfolio algorithms.</p>",
        "category": "market_update",
        "image_url": "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=400&fit=crop",
        "is_featured": True,
    },
    {
        "title": "Bitcoin Reaches New All-Time High Amid Institutional Adoption",
        "slug": "bitcoin-new-all-time-high-2026",
        "excerpt": "Bitcoin surged past previous records as major financial institutions continue to add cryptocurrency to their portfolios, signalling a new era of mainstream acceptance.",
        "content": "<p>Bitcoin has broken through its previous all-time high this week, driven by relentless buying pressure from institutional investors who are now treating it as a legitimate alternative asset class.</p><p>BlackRock's Bitcoin ETF alone saw inflows of over $1.2 billion in a single week, while MicroStrategy continues to expand its corporate treasury allocation.</p><h2>What This Means for Our Investors</h2><p>At Elite Wealth Capital, Bitcoin-backed investment plans are seeing some of their best returns in 18 months. Our professional trading desk has capitalised on this momentum, delivering exceptional daily ROI for clients enrolled in our Advanced and VIP plans.</p><p>If you haven't yet diversified into cryptocurrency-linked investment products, now is an excellent time to explore our range of plans.</p>",
        "category": "crypto",
        "image_url": "https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=400&h=300&fit=crop",
        "is_featured": False,
    },
    {
        "title": "New Feature: Enhanced Account Security & Two-Factor Authentication",
        "slug": "new-feature-enhanced-2fa",
        "excerpt": "We have upgraded our security infrastructure with email-based two-factor authentication to better protect your investments. Enable it in your account settings today.",
        "content": "<p>Security is at the heart of everything we do at Elite Wealth Capital. We are excited to announce several major security upgrades that make your account safer than ever.</p><h2>What's New</h2><ul><li><strong>Email 2FA:</strong> An additional one-time code is now sent to your registered email whenever you log in from an unrecognised device.</li><li><strong>Activity Logs:</strong> Review every login and transaction in your account history at any time.</li><li><strong>KYC Verification:</strong> Enhanced identity verification ensures only you can authorise withdrawals.</li></ul><p>We strongly encourage all users to complete their KYC verification and enable 2FA. Users with verified accounts enjoy higher withdrawal limits and priority support.</p>",
        "category": "platform_news",
        "image_url": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop",
        "is_featured": False,
    },
    {
        "title": "5 Investment Strategies for Volatile Markets",
        "slug": "5-investment-strategies-volatile-markets",
        "excerpt": "Learn how to protect and grow your portfolio during market uncertainty with these proven investment strategies used by professional traders.",
        "content": "<p>Market volatility is a fact of life for any investor. But volatility also creates opportunity — if you know how to position yourself. Here are five strategies our professional team uses to navigate uncertain conditions.</p><h2>1. Dollar-Cost Averaging</h2><p>Invest a fixed amount at regular intervals regardless of price. This smooths out the impact of short-term volatility and lowers your average cost over time.</p><h2>2. Diversification Across Asset Classes</h2><p>Spread your capital across crypto, equities, and fixed-income products. Our multi-asset investment plans do this automatically.</p><h2>3. Maintain a Cash Reserve</h2><p>Keep 10–20% of your portfolio liquid so you can take advantage of sudden dips without being forced to sell existing positions.</p><h2>4. Focus on Yield</h2><p>High-yield investment plans, like those offered by Elite Wealth Capital, provide predictable daily returns that compound effectively over time, regardless of market direction.</p><h2>5. Stay Informed</h2><p>Read our News & Updates section regularly and follow trusted market analysts. Informed decisions always outperform panic-driven ones.</p>",
        "category": "education",
        "image_url": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop",
        "is_featured": False,
    },
    {
        "title": "Elite Wealth Capital Expands Global Payment Options",
        "slug": "elite-wealth-capital-expands-payment-options",
        "excerpt": "We have added support for additional cryptocurrencies and faster fiat on-ramp options to make deposits and withdrawals more convenient for investors worldwide.",
        "content": "<p>We are pleased to announce a major expansion of our supported payment methods, making it easier than ever to fund your account and access your returns.</p><h2>New Deposit Options</h2><ul><li>Litecoin (LTC) – fast, low-fee transactions</li><li>USD Coin (USDC) – fully collateralised stablecoin</li><li>Additional regional bank transfer routes</li></ul><h2>Faster Withdrawals</h2><p>Our processing team now operates around the clock, meaning crypto withdrawals are typically processed within 2–6 hours. VIP account holders enjoy priority processing with a 1-hour target.</p><p>Log in to your dashboard to explore the new options, or contact our support team if you need assistance.</p>",
        "category": "platform_news",
        "image_url": "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400&h=300&fit=crop",
        "is_featured": False,
    },
]


def seed_articles(apps, schema_editor):
    NewsArticle = apps.get_model('dashboard', 'NewsArticle')
    now = timezone.now()
    for i, data in enumerate(SAMPLE_ARTICLES):
        # Only create if a matching slug doesn't already exist
        if not NewsArticle.objects.filter(slug=data['slug']).exists():
            from datetime import timedelta
            NewsArticle.objects.create(
                title=data['title'],
                slug=data['slug'],
                excerpt=data['excerpt'],
                content=data['content'],
                category=data['category'],
                image_url=data['image_url'],
                is_featured=data['is_featured'],
                is_published=True,
                published_at=now - timedelta(days=i * 3),
            )


def unseed_articles(apps, schema_editor):
    NewsArticle = apps.get_model('dashboard', 'NewsArticle')
    slugs = [a['slug'] for a in SAMPLE_ARTICLES]
    NewsArticle.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_articles, unseed_articles),
    ]
