# Generated by Django 6.0.2 on 2026-03-07 03:20
# Fixed to properly add virtual card fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_date_updated_customuser_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_virtual_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='card_status',
            field=models.CharField(choices=[('none', 'No Card'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='card_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='card_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='card_cvv',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='card_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='card_applied_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='card_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]