# Generated by Django 4.2.29 on 2026-03-14 03:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_virtual_card_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='Elite Wealth Capital', max_length=100)),
                ('site_tagline', models.CharField(default='Your Gateway to Financial Freedom', max_length=200)),
                ('company_email', models.EmailField(default='support@elitewealthcapita.uk', max_length=254)),
                ('company_phone', models.CharField(default='+1 (555) 123-4567', max_length=20)),
                ('company_address', models.TextField(default='123 Financial District, New York, NY 10001')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('telegram_url', models.URLField(blank=True, default='')),
                ('tawk_property_id', models.CharField(blank=True, help_text='Tawk.to Property ID', max_length=100)),
                ('enable_live_chat', models.BooleanField(default=True)),
                ('min_deposit', models.DecimalField(decimal_places=2, default=100, max_digits=15)),
                ('max_deposit', models.DecimalField(decimal_places=2, default=1000000, max_digits=15)),
                ('min_withdrawal', models.DecimalField(decimal_places=2, default=10, max_digits=15)),
                ('max_withdrawal', models.DecimalField(decimal_places=2, default=100000, max_digits=15)),
                ('withdrawal_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('referral_bonus_percent', models.DecimalField(decimal_places=2, default=5, help_text='% of first deposit', max_digits=5)),
                ('enable_referrals', models.BooleanField(default=True)),
                ('agent_commission_rate', models.DecimalField(decimal_places=2, default=10, help_text='Default agent commission %', max_digits=5)),
                ('enable_agent_applications', models.BooleanField(default=True)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('lockout_duration_minutes', models.IntegerField(default=30)),
                ('require_email_verification', models.BooleanField(default=True)),
                ('require_kyc_for_withdrawal', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(default='Site is under maintenance. Please check back later.')),
                ('meta_description', models.TextField(blank=True, default='Elite Wealth Capital - Professional investment platform')),
                ('meta_keywords', models.CharField(blank=True, default='investment, trading, forex, cryptocurrency', max_length=500)),
                ('hero_title', models.CharField(default='Invest Smart, Grow Wealthy', max_length=200)),
                ('hero_subtitle', models.TextField(default='Start your journey to financial freedom with our professional investment platform.')),
                ('footer_about', models.TextField(default='Elite Wealth Capital is a leading investment platform providing secure and profitable investment opportunities.')),
                ('copyright_text', models.CharField(default='© 2024 Elite Wealth Capital. All rights reserved.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
