# Generated by Django 4.2.29 on 2026-03-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_tawk_chat_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tawkchatlog',
            name='event_type',
            field=models.CharField(choices=[('chat:start', 'Chat Started'), ('chat:end', 'Chat Ended'), ('ticket:create', 'Ticket Created'), ('chat:transcript', 'Chat Transcript')], max_length=50),
        ),
    ]
