# Generated by Django 4.2.29 on 2026-03-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth as shown on the document', null=True),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='issue_date',
            field=models.DateField(blank=True, help_text='Date the document was issued', null=True),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='issuing_authority',
            field=models.CharField(blank=True, help_text='Issuing authority or department (e.g. Home Office, DMV)', max_length=200),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='issuing_country',
            field=models.CharField(default='', help_text='Country that issued the document', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='nationality',
            field=models.CharField(blank=True, help_text='Nationality as shown on the document', max_length=100),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_number',
            field=models.CharField(help_text='ID/passport number as shown on document', max_length=100),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('drivers_license', "Driver's License"), ('national_id', 'National ID Card'), ('residence_permit', 'Residence Permit'), ('voter_id', 'Voter ID Card'), ('tax_id', 'Tax Identification Card')], max_length=25),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='expires_at',
            field=models.DateField(blank=True, help_text='Expiry date of the document', null=True),
        ),
    ]
